-- Average delivery time

SELECT 
	U.ID AS USERID, U.NAMESURNAME,
	AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS AVGDELIVERYTIME,
	MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MAXDELIVERYTIME,
	MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MINDELIVERTTIME,
	SUM(O.TOTALPRICE) AS TOTALORDERAMOUNT,
	COUNT(O.ID) AS NUMBEROFORDER
	
	
FROM ORDERS O 
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID 
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY U.ID, U.NAMESURNAME
ORDER BY 6 DESC

