-- Order distribution by payment method

SELECT 
	DATEPART(YEAR,DATE_) AS YEAR_,
	DATEPART(MONTH,DATE_) AS MONTH_,
	CASE 
		WHEN PAYMENTTYPE=1 THEN 'CREDITCARD'
		WHEN PAYMENTTYPE=2 THEN 'BANK TRANSFER'
	END AS PAYMENTTYPE,
	SUM(PAYMENTTOTAL) AS PAYMENTTOTAL
FROM PAYMENTS

GROUP BY DATEPART(MONTH,DATE_), PAYMENTTYPE, DATEPART(YEAR,DATE_)
ORDER BY DATEPART(MONTH,DATE_), DATEPART(YEAR,DATE_)