-- Price analysis according to which month the products are sold the most

SELECT ITM.ITEMCODE, ITM.ITEMNAME,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MINPRICE,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS MAXPRICE,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS AVGPRICE,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOTALAMOUNT,
(
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS MONTH_ FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON O.ID =OD.ORDERID
WHERE OD.ITEMID = ITM.ID
GROUP BY DATEPART(MONTH,O.DATE_)
ORDER BY SUM(AMOUNT) DESC
) AS BESTSELLINGMONTH

FROM ITEMS ITM

WHERE ITM.ID IN 
(SELECT ITEMID FROM ORDERDETAILS)

ORDER BY 3
