-- Product Distribution Cy Category

SELECT 
	ITM.CATEGORY1, ITM.CATEGORY2,
	SUM(OD.LINETOTAL)AS TOTALORDELINE, 
	SUM(OD.AMOUNT) AS TOTALORDERAMOUNT,
	COUNT(OD.ID) AS TOTALNUMBEROFORDERS

FROM ORDERS O 
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

-- WHERE ITM.CATEGORY1='EV'

GROUP BY ITM.CATEGORY1, ITM.CATEGORY2
ORDER BY 3 DESC

