--Total Order Amount By the City

SELECT 
	CT.CITY AS CITYNAME,
	SUM(OD.LINETOTAL)AS TOTALORDELINE, 
	SUM(OD.AMOUNT) TOTALORDERAMOUNT,
	COUNT(OD.ID) AS TOTALNUMBEROFORDERS

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY CITY
ORDER BY 2 DESC
 
